# Generated by Django 6.0.2 on 2026-08-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hq', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('hq', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('description', models.TextField()),
                ('developer', models.ManyToManyField(related_name='games', to='web.developer')),
                ('genre', models.ManyToManyField(related_name='games', to='web.genre')),
                ('publisher', models.ManyToManyField(related_name='games', to='web.publisher')),
            ],
        ),
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='characters/')),
                ('description', models.TextField()),
                ('screen_time', models.IntegerField()),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='web.game')),
            ],
        ),
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='web.game')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshots',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='screenshots/')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='web.game')),
            ],
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timelines', to='web.game')),
            ],
        ),
    ]
