# Generated by Django 6.0.2 on 2026-08-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='achievements/'),
        ),
    ]
