# Generated by Django 6.0.2 on 2026-08-04 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_achievements_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Achievements',
            new_name='Achievement',
        ),
        migrations.RenameModel(
            old_name='Characters',
            new_name='Character',
        ),
        migrations.RenameModel(
            old_name='Screenshots',
            new_name='Screenshot',
        ),
    ]
