# Generated by Django 6.0.2 on 2026-08-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_rename_achievements_achievement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
    ]
