# Generated by Django 6.0.2 on 2026-08-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_game_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='img',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
