# Generated by Django 6.0.2 on 2026-08-04 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_achievement_img_alter_character_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='screenshot',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
    ]
