# Generated by Django 6.0.2 on 2026-08-04 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_character_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='achievement/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='character/'),
        ),
        migrations.AlterField(
            model_name='character',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='character_screenshots/'),
        ),
        migrations.AlterField(
            model_name='game',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='posters/'),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
    ]
