# Generated by Django 6.0.2 on 2026-08-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_game_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeline',
            name='date',
        ),
        migrations.RemoveField(
            model_name='timeline',
            name='event',
        ),
        migrations.AddField(
            model_name='timeline',
            name='completionist_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='main_story_playtime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='playtime_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
