# Generated by Django 6.0.2 on 2026-08-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_remove_timeline_date_remove_timeline_event_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['id']},
        ),
    ]
