# Generated by Django 6.0.2 on 2026-08-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_character_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='screenshot',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
